import { Contributor } from "@/types";

export const mockContributors: Contributor[] = [
  {
    id: "u1",
    name: "Alice Chen",
    address: "0xABCd...1234",
    skills: ["React", "TypeScript", "Next.js", "TailwindCSS", "UI/UX"],
    reputation: 94,
    pricePerTask: 0.04,
    completedTasks: 28,
  },
  {
    id: "u2",
    name: "Bob Martinez",
    address: "0x2345...BCDE",
    skills: ["Solidity", "Ethereum", "Web3.js", "Smart Contracts", "Hardhat"],
    reputation: 91,
    pricePerTask: 0.07,
    completedTasks: 19,
  },
  {
    id: "u3",
    name: "Carol Kim",
    address: "0x3456...CDEF",
    skills: ["Node.js", "REST API", "PostgreSQL", "Docker", "TypeScript"],
    reputation: 87,
    pricePerTask: 0.05,
    completedTasks: 34,
  },
  {
    id: "u4",
    name: "Dan Rivera",
    address: "0x4567...DEF0",
    skills: ["Python", "Machine Learning", "OpenAI API", "FastAPI", "Data Science"],
    reputation: 89,
    pricePerTask: 0.06,
    completedTasks: 22,
  },
  {
    id: "u5",
    name: "Eva Patel",
    address: "0x5678...EF01",
    skills: ["React", "Node.js", "MongoDB", "GraphQL", "AWS"],
    reputation: 82,
    pricePerTask: 0.045,
    completedTasks: 15,
  },
  {
    id: "u6",
    name: "Frank Liu",
    address: "0x6789...F012",
    skills: ["Solidity", "DeFi", "Hardhat", "OpenZeppelin", "Ethers.js"],
    reputation: 96,
    pricePerTask: 0.09,
    completedTasks: 41,
  },
  {
    id: "u7",
    name: "Grace Okonkwo",
    address: "0x7890...0123",
    skills: ["Vue.js", "TypeScript", "Figma", "CSS", "Accessibility"],
    reputation: 78,
    pricePerTask: 0.035,
    completedTasks: 11,
  },
  {
    id: "u8",
    name: "Hiro Tanaka",
    address: "0x8901...1234",
    skills: ["Rust", "WebAssembly", "C++", "Systems Programming", "Cryptography"],
    reputation: 93,
    pricePerTask: 0.1,
    completedTasks: 17,
  },
];
